### PR TITLE
chore(tests): updating the syntax to the new ES2017

### PR DESCRIPTION
**Pull request by paulohp**
I'm planning to clean up the code a little bit using the newest syntax of ES2017. At the same time, I get used to the lib and tests.

@Hackdom @joshuahannan please take a look and let me know your thoughts.

### CODE REVIEW

**Comment by Hackdom** [comment]
Yeah this looks great Paulo. Are you ready for a merge on this?

**Comment by paulohp** [comment]
@Hackdom not yet, still refactoring the remaining tests. this will probably be finished late tomorrow.

**Comment by Hackdom** [comment]
ok, no problem, looks great man

**Comment by Hackdom** [comment]
This looks great to me, Josh do you have anything else?

**Comment by paulohp** [comment]
I’m still updating the variables names, will send the commit first thing
tomorrow.

**Comment by joshuahannan** [comment]
Everything looks great to me. So clean looking!

**Comment by joshuahannan** [comment]
I like the changes. a lot easier to read with the new variable names.

**Pull request merged**
